FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Пакеты:
RUN apt-get update && apt-get install -y \
    python3 python3-pip \ 
    python3-opencv \
    v4l-utils \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY capture.py /app/capture.py

CMD ["python3", "/app/capture.py"]